"""
installer/gen_version_info.py

Generates installer/version_info.txt from version.py.
PyInstaller uses version_info.txt to embed Windows file-property metadata
(visible in Explorer → right-click SanjINSIGHT.exe → Properties → Details).

Run this script before every release, then commit the updated file:

    python installer/gen_version_info.py

CI runs it automatically as part of the build-installer workflow.
"""

import os
import sys

# Allow running from any directory (project root or installer/)
_SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
_PROJECT_DIR = os.path.dirname(_SCRIPT_DIR)
sys.path.insert(0, _PROJECT_DIR)

from version import __version__, APP_NAME, APP_VENDOR, VERSION_TUPLE  # noqa: E402

major, minor, patch = VERSION_TUPLE
build = 0   # 4th field — always 0; use Git tags for release tracking

content = f"""\
# Windows version resource for {APP_NAME}
# Auto-generated by installer/gen_version_info.py — do not edit manually.
# Re-generate with:  python installer/gen_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(u'040904B0', [
        StringStruct(u'CompanyName',      u'{APP_VENDOR}, LLC'),
        StringStruct(u'FileDescription',  u'{APP_NAME} Thermal Analysis Software'),
        StringStruct(u'FileVersion',      u'{major}.{minor}.{patch}.{build}'),
        StringStruct(u'InternalName',     u'{APP_NAME}'),
        StringStruct(u'LegalCopyright',   u'Copyright 2026 {APP_VENDOR}, LLC.'),
        StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
        StringStruct(u'ProductName',      u'{APP_VENDOR} {APP_NAME}'),
        StringStruct(u'ProductVersion',   u'{major}.{minor}.{patch}.{build}'),
      ])
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""

out_path = os.path.join(_SCRIPT_DIR, 'version_info.txt')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Generated: {out_path}  ({APP_NAME} v{__version__})")
